general:
  productiveBranch: 'consumer-test-neo'
  collectTelemetryData: false
stages:
  productionDeployment:
    neoTargets:
      - host: 'eu1.hana.ondemand.com'
        account: 's7am47zded'
        application: 'devopsdockerimagesitonneo'
        credentialsId: 'devops-docker-images-IT-cf'
        runtime: 'neo-javaee7-wp'
        runtimeVersion: '1'
