general:
  inferBuildTool: true
  inferProjectName: true
  productiveBranch: 'consumer-test'
  collectTelemetryData: false
steps:
  artifactPrepareVersion:
    versioningType: 'cloud_noTag'
  cloudFoundryDeploy:
    dockerImage: 'ppiper/cf-cli:6'
    useGoStep: true
    apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
    deployTool: cf_native
    deployType: standard
    org: piper
    space: infra-testing
    appName: 'devops-docker-images-IT'
    manifest: manifest.yml
  mavenExecute:
    dockerImage: 'maven:3.6.3-jdk-11'
  mtaBuild:
    buildTarget: 'CF'
    mtaBuildTool: 'cloudMbt'
stages:
  Confirm:
    manualConfirmation: false
  Release:
    cfCreateServices:
      - serviceManifest: 'services-manifest.yml'
        space: 'infra-testing'
        org: 'piper'
        credentialsId: 'devops-docker-images-IT-cf'
    cfTargets:
      - org: 'piper'
        space: 'infra-testing'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: 'devops-docker-images-IT'
        manifest: 'manifest.yml'
        credentialsId: 'devops-docker-images-IT-cf'
